// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AboutBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout authorsLayout;

  @NonNull
  public final Button changelog;

  @NonNull
  public final TextView copyright;

  @NonNull
  public final Button issues;

  @NonNull
  public final LinearLayout licenseLayout;

  @NonNull
  public final Button source;

  @NonNull
  public final TextView version;

  @NonNull
  public final LinearLayout versionLayout;

  private AboutBinding(@NonNull LinearLayout rootView, @NonNull LinearLayout authorsLayout,
      @NonNull Button changelog, @NonNull TextView copyright, @NonNull Button issues,
      @NonNull LinearLayout licenseLayout, @NonNull Button source, @NonNull TextView version,
      @NonNull LinearLayout versionLayout) {
    this.rootView = rootView;
    this.authorsLayout = authorsLayout;
    this.changelog = changelog;
    this.copyright = copyright;
    this.issues = issues;
    this.licenseLayout = licenseLayout;
    this.source = source;
    this.version = version;
    this.versionLayout = versionLayout;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AboutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AboutBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.about, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AboutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.authorsLayout;
      LinearLayout authorsLayout = ViewBindings.findChildViewById(rootView, id);
      if (authorsLayout == null) {
        break missingId;
      }

      id = R.id.changelog;
      Button changelog = ViewBindings.findChildViewById(rootView, id);
      if (changelog == null) {
        break missingId;
      }

      id = R.id.copyright;
      TextView copyright = ViewBindings.findChildViewById(rootView, id);
      if (copyright == null) {
        break missingId;
      }

      id = R.id.issues;
      Button issues = ViewBindings.findChildViewById(rootView, id);
      if (issues == null) {
        break missingId;
      }

      id = R.id.licenseLayout;
      LinearLayout licenseLayout = ViewBindings.findChildViewById(rootView, id);
      if (licenseLayout == null) {
        break missingId;
      }

      id = R.id.source;
      Button source = ViewBindings.findChildViewById(rootView, id);
      if (source == null) {
        break missingId;
      }

      id = R.id.version;
      TextView version = ViewBindings.findChildViewById(rootView, id);
      if (version == null) {
        break missingId;
      }

      id = R.id.versionLayout;
      LinearLayout versionLayout = ViewBindings.findChildViewById(rootView, id);
      if (versionLayout == null) {
        break missingId;
      }

      return new AboutBinding((LinearLayout) rootView, authorsLayout, changelog, copyright, issues,
          licenseLayout, source, version, versionLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
