// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class ActionbarPulldownMenuTopButtonBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final TextView topButtonDate;

  @NonNull
  public final TextView topButtonLunar;

  @NonNull
  public final TextView topButtonWeekday;

  private ActionbarPulldownMenuTopButtonBinding(@NonNull RelativeLayout rootView,
      @NonNull TextView topButtonDate, @NonNull TextView topButtonLunar,
      @NonNull TextView topButtonWeekday) {
    this.rootView = rootView;
    this.topButtonDate = topButtonDate;
    this.topButtonLunar = topButtonLunar;
    this.topButtonWeekday = topButtonWeekday;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActionbarPulldownMenuTopButtonBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActionbarPulldownMenuTopButtonBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.actionbar_pulldown_menu_top_button, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActionbarPulldownMenuTopButtonBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.top_button_date;
      TextView topButtonDate = ViewBindings.findChildViewById(rootView, id);
      if (topButtonDate == null) {
        break missingId;
      }

      id = R.id.top_button_lunar;
      TextView topButtonLunar = ViewBindings.findChildViewById(rootView, id);
      if (topButtonLunar == null) {
        break missingId;
      }

      id = R.id.top_button_weekday;
      TextView topButtonWeekday = ViewBindings.findChildViewById(rootView, id);
      if (topButtonWeekday == null) {
        break missingId;
      }

      return new ActionbarPulldownMenuTopButtonBinding((RelativeLayout) rootView, topButtonDate,
          topButtonLunar, topButtonWeekday);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
