// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AddOfflineCalendarDialogBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextInputEditText offlineCalendarName;

  @NonNull
  public final TextInputLayout offlineCalendarNameLayout;

  private AddOfflineCalendarDialogBinding(@NonNull LinearLayout rootView,
      @NonNull TextInputEditText offlineCalendarName,
      @NonNull TextInputLayout offlineCalendarNameLayout) {
    this.rootView = rootView;
    this.offlineCalendarName = offlineCalendarName;
    this.offlineCalendarNameLayout = offlineCalendarNameLayout;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AddOfflineCalendarDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AddOfflineCalendarDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.add_offline_calendar_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AddOfflineCalendarDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.offline_calendar_name;
      TextInputEditText offlineCalendarName = ViewBindings.findChildViewById(rootView, id);
      if (offlineCalendarName == null) {
        break missingId;
      }

      id = R.id.offline_calendar_name_layout;
      TextInputLayout offlineCalendarNameLayout = ViewBindings.findChildViewById(rootView, id);
      if (offlineCalendarNameLayout == null) {
        break missingId;
      }

      return new AddOfflineCalendarDialogBinding((LinearLayout) rootView, offlineCalendarName,
          offlineCalendarNameLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
