// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.StickyHeaderListView;
import com.android.calendar.agenda.AgendaListView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AgendaFragmentBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final FrameLayout agendaEventInfo;

  @NonNull
  public final AgendaListView agendaEventsList;

  @NonNull
  public final StickyHeaderListView agendaStickyHeaderList;

  private AgendaFragmentBinding(@NonNull LinearLayout rootView,
      @NonNull FrameLayout agendaEventInfo, @NonNull AgendaListView agendaEventsList,
      @NonNull StickyHeaderListView agendaStickyHeaderList) {
    this.rootView = rootView;
    this.agendaEventInfo = agendaEventInfo;
    this.agendaEventsList = agendaEventsList;
    this.agendaStickyHeaderList = agendaStickyHeaderList;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AgendaFragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AgendaFragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.agenda_fragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AgendaFragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.agenda_event_info;
      FrameLayout agendaEventInfo = ViewBindings.findChildViewById(rootView, id);
      if (agendaEventInfo == null) {
        break missingId;
      }

      id = R.id.agenda_events_list;
      AgendaListView agendaEventsList = ViewBindings.findChildViewById(rootView, id);
      if (agendaEventsList == null) {
        break missingId;
      }

      id = R.id.agenda_sticky_header_list;
      StickyHeaderListView agendaStickyHeaderList = ViewBindings.findChildViewById(rootView, id);
      if (agendaStickyHeaderList == null) {
        break missingId;
      }

      return new AgendaFragmentBinding((LinearLayout) rootView, agendaEventInfo, agendaEventsList,
          agendaStickyHeaderList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
