// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.GridLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.ColorChipView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AgendaItemBinding implements ViewBinding {
  @NonNull
  private final GridLayout rootView;

  @NonNull
  public final ColorChipView agendaItemColor;

  @NonNull
  public final LinearLayout agendaItemTextContainer;

  @NonNull
  public final GridLayout content;

  @NonNull
  public final ImageView selectedMarker;

  @NonNull
  public final TextView title;

  @NonNull
  public final TextView when;

  @NonNull
  public final TextView where;

  private AgendaItemBinding(@NonNull GridLayout rootView, @NonNull ColorChipView agendaItemColor,
      @NonNull LinearLayout agendaItemTextContainer, @NonNull GridLayout content,
      @NonNull ImageView selectedMarker, @NonNull TextView title, @NonNull TextView when,
      @NonNull TextView where) {
    this.rootView = rootView;
    this.agendaItemColor = agendaItemColor;
    this.agendaItemTextContainer = agendaItemTextContainer;
    this.content = content;
    this.selectedMarker = selectedMarker;
    this.title = title;
    this.when = when;
    this.where = where;
  }

  @Override
  @NonNull
  public GridLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AgendaItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AgendaItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.agenda_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AgendaItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.agenda_item_color;
      ColorChipView agendaItemColor = ViewBindings.findChildViewById(rootView, id);
      if (agendaItemColor == null) {
        break missingId;
      }

      id = R.id.agenda_item_text_container;
      LinearLayout agendaItemTextContainer = ViewBindings.findChildViewById(rootView, id);
      if (agendaItemTextContainer == null) {
        break missingId;
      }

      GridLayout content = (GridLayout) rootView;

      id = R.id.selected_marker;
      ImageView selectedMarker = ViewBindings.findChildViewById(rootView, id);
      if (selectedMarker == null) {
        break missingId;
      }

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.when;
      TextView when = ViewBindings.findChildViewById(rootView, id);
      if (when == null) {
        break missingId;
      }

      id = R.id.where;
      TextView where = ViewBindings.findChildViewById(rootView, id);
      if (where == null) {
        break missingId;
      }

      return new AgendaItemBinding((GridLayout) rootView, agendaItemColor, agendaItemTextContainer,
          content, selectedMarker, title, when, where);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
