// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AgendaDayBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final TextView date;

  @NonNull
  public final TextView day;

  @NonNull
  public final View topDividerPastPresent;

  @NonNull
  public final View topDividerSimple;

  private AgendaDayBinding(@NonNull View rootView, @NonNull TextView date, @NonNull TextView day,
      @NonNull View topDividerPastPresent, @NonNull View topDividerSimple) {
    this.rootView = rootView;
    this.date = date;
    this.day = day;
    this.topDividerPastPresent = topDividerPastPresent;
    this.topDividerSimple = topDividerSimple;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static AgendaDayBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AgendaDayBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.agenda_day, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AgendaDayBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.date;
      TextView date = ViewBindings.findChildViewById(rootView, id);
      if (date == null) {
        break missingId;
      }

      id = R.id.day;
      TextView day = ViewBindings.findChildViewById(rootView, id);
      if (day == null) {
        break missingId;
      }

      id = R.id.top_divider_past_present;
      View topDividerPastPresent = ViewBindings.findChildViewById(rootView, id);
      if (topDividerPastPresent == null) {
        break missingId;
      }

      id = R.id.top_divider_simple;
      View topDividerSimple = ViewBindings.findChildViewById(rootView, id);
      if (topDividerSimple == null) {
        break missingId;
      }

      return new AgendaDayBinding(rootView, date, day, topDividerPastPresent, topDividerSimple);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
