// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AllInOneBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final FrameLayout calendarList;

  @NonNull
  public final TextView dateBar;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout-sw600dp/</li>
   *   <li>layout-sw600dp-w960dp-h527dp-land/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout/</li>
   *   <li>layout-land/</li>
   * </ul>
   */
  @Nullable
  public final LinearLayout dateGroup;

  @NonNull
  public final TextView homeTime;

  @NonNull
  public final FrameLayout mainPane;

  @NonNull
  public final FrameLayout miniMonth;

  @NonNull
  public final View miniMonthContainer;

  @NonNull
  public final FrameLayout secondaryPane;

  @NonNull
  public final TextView weekNum;

  private AllInOneBinding(@NonNull View rootView, @NonNull FrameLayout calendarList,
      @NonNull TextView dateBar, @Nullable LinearLayout dateGroup, @NonNull TextView homeTime,
      @NonNull FrameLayout mainPane, @NonNull FrameLayout miniMonth,
      @NonNull View miniMonthContainer, @NonNull FrameLayout secondaryPane,
      @NonNull TextView weekNum) {
    this.rootView = rootView;
    this.calendarList = calendarList;
    this.dateBar = dateBar;
    this.dateGroup = dateGroup;
    this.homeTime = homeTime;
    this.mainPane = mainPane;
    this.miniMonth = miniMonth;
    this.miniMonthContainer = miniMonthContainer;
    this.secondaryPane = secondaryPane;
    this.weekNum = weekNum;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static AllInOneBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AllInOneBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.all_in_one, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AllInOneBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.calendar_list;
      FrameLayout calendarList = ViewBindings.findChildViewById(rootView, id);
      if (calendarList == null) {
        break missingId;
      }

      id = R.id.date_bar;
      TextView dateBar = ViewBindings.findChildViewById(rootView, id);
      if (dateBar == null) {
        break missingId;
      }

      id = R.id.date_group;
      LinearLayout dateGroup = ViewBindings.findChildViewById(rootView, id);

      id = R.id.home_time;
      TextView homeTime = ViewBindings.findChildViewById(rootView, id);
      if (homeTime == null) {
        break missingId;
      }

      id = R.id.main_pane;
      FrameLayout mainPane = ViewBindings.findChildViewById(rootView, id);
      if (mainPane == null) {
        break missingId;
      }

      id = R.id.mini_month;
      FrameLayout miniMonth = ViewBindings.findChildViewById(rootView, id);
      if (miniMonth == null) {
        break missingId;
      }

      id = R.id.mini_month_container;
      View miniMonthContainer = ViewBindings.findChildViewById(rootView, id);
      if (miniMonthContainer == null) {
        break missingId;
      }

      id = R.id.secondary_pane;
      FrameLayout secondaryPane = ViewBindings.findChildViewById(rootView, id);
      if (secondaryPane == null) {
        break missingId;
      }

      id = R.id.week_num;
      TextView weekNum = ViewBindings.findChildViewById(rootView, id);
      if (weekNum == null) {
        break missingId;
      }

      return new AllInOneBinding(rootView, calendarList, dateBar, dateGroup, homeTime, mainPane,
          miniMonth, miniMonthContainer, secondaryPane, weekNum);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
