// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AppwidgetNoEventsBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout appwidgetNoEvents;

  @NonNull
  public final TextView noEvents;

  private AppwidgetNoEventsBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout appwidgetNoEvents, @NonNull TextView noEvents) {
    this.rootView = rootView;
    this.appwidgetNoEvents = appwidgetNoEvents;
    this.noEvents = noEvents;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AppwidgetNoEventsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AppwidgetNoEventsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.appwidget_no_events, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AppwidgetNoEventsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout appwidgetNoEvents = (LinearLayout) rootView;

      id = R.id.no_events;
      TextView noEvents = ViewBindings.findChildViewById(rootView, id);
      if (noEvents == null) {
        break missingId;
      }

      return new AppwidgetNoEventsBinding((LinearLayout) rootView, appwidgetNoEvents, noEvents);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
