// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class AppwidgetBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView date;

  @NonNull
  public final TextView dayOfWeek;

  @NonNull
  public final ListView eventsList;

  @NonNull
  public final RelativeLayout header;

  @NonNull
  public final ImageView ivAdd;

  @NonNull
  public final LinearLayout widgetBackground;

  private AppwidgetBinding(@NonNull LinearLayout rootView, @NonNull TextView date,
      @NonNull TextView dayOfWeek, @NonNull ListView eventsList, @NonNull RelativeLayout header,
      @NonNull ImageView ivAdd, @NonNull LinearLayout widgetBackground) {
    this.rootView = rootView;
    this.date = date;
    this.dayOfWeek = dayOfWeek;
    this.eventsList = eventsList;
    this.header = header;
    this.ivAdd = ivAdd;
    this.widgetBackground = widgetBackground;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AppwidgetBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AppwidgetBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.appwidget, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AppwidgetBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.date;
      TextView date = ViewBindings.findChildViewById(rootView, id);
      if (date == null) {
        break missingId;
      }

      id = R.id.day_of_week;
      TextView dayOfWeek = ViewBindings.findChildViewById(rootView, id);
      if (dayOfWeek == null) {
        break missingId;
      }

      id = R.id.events_list;
      ListView eventsList = ViewBindings.findChildViewById(rootView, id);
      if (eventsList == null) {
        break missingId;
      }

      id = R.id.header;
      RelativeLayout header = ViewBindings.findChildViewById(rootView, id);
      if (header == null) {
        break missingId;
      }

      id = R.id.iv_add;
      ImageView ivAdd = ViewBindings.findChildViewById(rootView, id);
      if (ivAdd == null) {
        break missingId;
      }

      LinearLayout widgetBackground = (LinearLayout) rootView;

      return new AppwidgetBinding((LinearLayout) rootView, date, dayOfWeek, eventsList, header,
          ivAdd, widgetBackground);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
