// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class BubbleEventBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout bubbleLayout;

  @NonNull
  public final TextView eventTitle;

  @NonNull
  public final ImageView reminderIcon;

  @NonNull
  public final ImageView repeatIcon;

  @NonNull
  public final TextView time;

  @NonNull
  public final TextView where;

  private BubbleEventBinding(@NonNull LinearLayout rootView, @NonNull LinearLayout bubbleLayout,
      @NonNull TextView eventTitle, @NonNull ImageView reminderIcon, @NonNull ImageView repeatIcon,
      @NonNull TextView time, @NonNull TextView where) {
    this.rootView = rootView;
    this.bubbleLayout = bubbleLayout;
    this.eventTitle = eventTitle;
    this.reminderIcon = reminderIcon;
    this.repeatIcon = repeatIcon;
    this.time = time;
    this.where = where;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static BubbleEventBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static BubbleEventBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.bubble_event, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static BubbleEventBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout bubbleLayout = (LinearLayout) rootView;

      id = R.id.event_title;
      TextView eventTitle = ViewBindings.findChildViewById(rootView, id);
      if (eventTitle == null) {
        break missingId;
      }

      id = R.id.reminder_icon;
      ImageView reminderIcon = ViewBindings.findChildViewById(rootView, id);
      if (reminderIcon == null) {
        break missingId;
      }

      id = R.id.repeat_icon;
      ImageView repeatIcon = ViewBindings.findChildViewById(rootView, id);
      if (repeatIcon == null) {
        break missingId;
      }

      id = R.id.time;
      TextView time = ViewBindings.findChildViewById(rootView, id);
      if (time == null) {
        break missingId;
      }

      id = R.id.where;
      TextView where = ViewBindings.findChildViewById(rootView, id);
      if (where == null) {
        break missingId;
      }

      return new BubbleEventBinding((LinearLayout) rootView, bubbleLayout, eventTitle, reminderIcon,
          repeatIcon, time, where);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
