// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class CalendarsSpinnerItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView accountName;

  @NonNull
  public final TextView calendarName;

  private CalendarsSpinnerItemBinding(@NonNull LinearLayout rootView, @NonNull TextView accountName,
      @NonNull TextView calendarName) {
    this.rootView = rootView;
    this.accountName = accountName;
    this.calendarName = calendarName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static CalendarsSpinnerItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static CalendarsSpinnerItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.calendars_spinner_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static CalendarsSpinnerItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.account_name;
      TextView accountName = ViewBindings.findChildViewById(rootView, id);
      if (accountName == null) {
        break missingId;
      }

      id = R.id.calendar_name;
      TextView calendarName = ViewBindings.findChildViewById(rootView, id);
      if (calendarName == null) {
        break missingId;
      }

      return new CalendarsSpinnerItemBinding((LinearLayout) rootView, accountName, calendarName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
