// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class ChipsAutocompleteRecipientDropdownItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final View chipAutocompleteBottomDivider;

  @NonNull
  public final View chipAutocompleteTopDivider;

  @NonNull
  public final View chipPermissionBottomDivider;

  @NonNull
  public final LinearLayout chipPermissionWrapper;

  @NonNull
  public final LinearLayout chipPersonWrapper;

  private ChipsAutocompleteRecipientDropdownItemBinding(@NonNull LinearLayout rootView,
      @NonNull View chipAutocompleteBottomDivider, @NonNull View chipAutocompleteTopDivider,
      @NonNull View chipPermissionBottomDivider, @NonNull LinearLayout chipPermissionWrapper,
      @NonNull LinearLayout chipPersonWrapper) {
    this.rootView = rootView;
    this.chipAutocompleteBottomDivider = chipAutocompleteBottomDivider;
    this.chipAutocompleteTopDivider = chipAutocompleteTopDivider;
    this.chipPermissionBottomDivider = chipPermissionBottomDivider;
    this.chipPermissionWrapper = chipPermissionWrapper;
    this.chipPersonWrapper = chipPersonWrapper;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ChipsAutocompleteRecipientDropdownItemBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ChipsAutocompleteRecipientDropdownItemBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.chips_autocomplete_recipient_dropdown_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ChipsAutocompleteRecipientDropdownItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.chip_autocomplete_bottom_divider;
      View chipAutocompleteBottomDivider = ViewBindings.findChildViewById(rootView, id);
      if (chipAutocompleteBottomDivider == null) {
        break missingId;
      }

      id = R.id.chip_autocomplete_top_divider;
      View chipAutocompleteTopDivider = ViewBindings.findChildViewById(rootView, id);
      if (chipAutocompleteTopDivider == null) {
        break missingId;
      }

      id = R.id.chip_permission_bottom_divider;
      View chipPermissionBottomDivider = ViewBindings.findChildViewById(rootView, id);
      if (chipPermissionBottomDivider == null) {
        break missingId;
      }

      id = R.id.chip_permission_wrapper;
      LinearLayout chipPermissionWrapper = ViewBindings.findChildViewById(rootView, id);
      if (chipPermissionWrapper == null) {
        break missingId;
      }

      id = R.id.chip_person_wrapper;
      LinearLayout chipPersonWrapper = ViewBindings.findChildViewById(rootView, id);
      if (chipPersonWrapper == null) {
        break missingId;
      }

      return new ChipsAutocompleteRecipientDropdownItemBinding((LinearLayout) rootView,
          chipAutocompleteBottomDivider, chipAutocompleteTopDivider, chipPermissionBottomDivider,
          chipPermissionWrapper, chipPersonWrapper);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
