// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class ColorPickerSwatchBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView colorPickerCheckmark;

  @NonNull
  public final ImageView colorPickerSwatch;

  private ColorPickerSwatchBinding(@NonNull View rootView, @NonNull ImageView colorPickerCheckmark,
      @NonNull ImageView colorPickerSwatch) {
    this.rootView = rootView;
    this.colorPickerCheckmark = colorPickerCheckmark;
    this.colorPickerSwatch = colorPickerSwatch;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ColorPickerSwatchBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.color_picker_swatch, parent);
    return bind(parent);
  }

  @NonNull
  public static ColorPickerSwatchBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.color_picker_checkmark;
      ImageView colorPickerCheckmark = ViewBindings.findChildViewById(rootView, id);
      if (colorPickerCheckmark == null) {
        break missingId;
      }

      id = R.id.color_picker_swatch;
      ImageView colorPickerSwatch = ViewBindings.findChildViewById(rootView, id);
      if (colorPickerSwatch == null) {
        break missingId;
      }

      return new ColorPickerSwatchBinding(rootView, colorPickerCheckmark, colorPickerSwatch);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
