// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.QuickContactBadge;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class ContactItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final QuickContactBadge badge;

  @NonNull
  public final ImageButton contactRemove;

  @NonNull
  public final View contactSeparator;

  @NonNull
  public final TextView name;

  private ContactItemBinding(@NonNull LinearLayout rootView, @NonNull QuickContactBadge badge,
      @NonNull ImageButton contactRemove, @NonNull View contactSeparator, @NonNull TextView name) {
    this.rootView = rootView;
    this.badge = badge;
    this.contactRemove = contactRemove;
    this.contactSeparator = contactSeparator;
    this.name = name;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ContactItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ContactItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.contact_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ContactItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.badge;
      QuickContactBadge badge = ViewBindings.findChildViewById(rootView, id);
      if (badge == null) {
        break missingId;
      }

      id = R.id.contact_remove;
      ImageButton contactRemove = ViewBindings.findChildViewById(rootView, id);
      if (contactRemove == null) {
        break missingId;
      }

      id = R.id.contact_separator;
      View contactSeparator = ViewBindings.findChildViewById(rootView, id);
      if (contactSeparator == null) {
        break missingId;
      }

      id = R.id.name;
      TextView name = ViewBindings.findChildViewById(rootView, id);
      if (name == null) {
        break missingId;
      }

      return new ContactItemBinding((LinearLayout) rootView, badge, contactRemove, contactSeparator,
          name);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
