// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class CreateEventDialogBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView accountName;

  @NonNull
  public final TextView calendarName;

  @NonNull
  public final View color;

  @NonNull
  public final TextView eventDay;

  @NonNull
  public final EditText eventTitle;

  private CreateEventDialogBinding(@NonNull LinearLayout rootView, @NonNull TextView accountName,
      @NonNull TextView calendarName, @NonNull View color, @NonNull TextView eventDay,
      @NonNull EditText eventTitle) {
    this.rootView = rootView;
    this.accountName = accountName;
    this.calendarName = calendarName;
    this.color = color;
    this.eventDay = eventDay;
    this.eventTitle = eventTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static CreateEventDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static CreateEventDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.create_event_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static CreateEventDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.account_name;
      TextView accountName = ViewBindings.findChildViewById(rootView, id);
      if (accountName == null) {
        break missingId;
      }

      id = R.id.calendar_name;
      TextView calendarName = ViewBindings.findChildViewById(rootView, id);
      if (calendarName == null) {
        break missingId;
      }

      id = R.id.color;
      View color = ViewBindings.findChildViewById(rootView, id);
      if (color == null) {
        break missingId;
      }

      id = R.id.event_day;
      TextView eventDay = ViewBindings.findChildViewById(rootView, id);
      if (eventDay == null) {
        break missingId;
      }

      id = R.id.event_title;
      EditText eventTitle = ViewBindings.findChildViewById(rootView, id);
      if (eventTitle == null) {
        break missingId;
      }

      return new CreateEventDialogBinding((LinearLayout) rootView, accountName, calendarName, color,
          eventDay, eventTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
