// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EditEventSingleColumnBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final View colorChip;

  @NonNull
  public final LinearLayout editEvent;

  @NonNull
  public final TextView loadingMessage;

  @NonNull
  public final ScrollView scrollView;

  private EditEventSingleColumnBinding(@NonNull LinearLayout rootView, @NonNull View colorChip,
      @NonNull LinearLayout editEvent, @NonNull TextView loadingMessage,
      @NonNull ScrollView scrollView) {
    this.rootView = rootView;
    this.colorChip = colorChip;
    this.editEvent = editEvent;
    this.loadingMessage = loadingMessage;
    this.scrollView = scrollView;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EditEventSingleColumnBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EditEventSingleColumnBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.edit_event_single_column, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EditEventSingleColumnBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.color_chip;
      View colorChip = ViewBindings.findChildViewById(rootView, id);
      if (colorChip == null) {
        break missingId;
      }

      LinearLayout editEvent = (LinearLayout) rootView;

      id = R.id.loading_message;
      TextView loadingMessage = ViewBindings.findChildViewById(rootView, id);
      if (loadingMessage == null) {
        break missingId;
      }

      id = R.id.scroll_view;
      ScrollView scrollView = ViewBindings.findChildViewById(rootView, id);
      if (scrollView == null) {
        break missingId;
      }

      return new EditEventSingleColumnBinding((LinearLayout) rootView, colorChip, editEvent,
          loadingMessage, scrollView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
