// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.ImageButton;
import android.widget.Spinner;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EditReminderItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Spinner reminderMethodValue;

  @NonNull
  public final CheckBox reminderMinutesSign;

  @NonNull
  public final Spinner reminderMinutesValue;

  @NonNull
  public final ImageButton reminderRemove;

  private EditReminderItemBinding(@NonNull ConstraintLayout rootView,
      @NonNull Spinner reminderMethodValue, @NonNull CheckBox reminderMinutesSign,
      @NonNull Spinner reminderMinutesValue, @NonNull ImageButton reminderRemove) {
    this.rootView = rootView;
    this.reminderMethodValue = reminderMethodValue;
    this.reminderMinutesSign = reminderMinutesSign;
    this.reminderMinutesValue = reminderMinutesValue;
    this.reminderRemove = reminderRemove;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EditReminderItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EditReminderItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.edit_reminder_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EditReminderItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.reminder_method_value;
      Spinner reminderMethodValue = ViewBindings.findChildViewById(rootView, id);
      if (reminderMethodValue == null) {
        break missingId;
      }

      id = R.id.reminder_minutes_sign;
      CheckBox reminderMinutesSign = ViewBindings.findChildViewById(rootView, id);
      if (reminderMinutesSign == null) {
        break missingId;
      }

      id = R.id.reminder_minutes_value;
      Spinner reminderMinutesValue = ViewBindings.findChildViewById(rootView, id);
      if (reminderMinutesValue == null) {
        break missingId;
      }

      id = R.id.reminder_remove;
      ImageButton reminderRemove = ViewBindings.findChildViewById(rootView, id);
      if (reminderRemove == null) {
        break missingId;
      }

      return new EditReminderItemBinding((ConstraintLayout) rootView, reminderMethodValue,
          reminderMinutesSign, reminderMinutesValue, reminderRemove);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
