// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Group;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.chips.RecipientEditTextView;
import com.google.android.material.materialswitch.MaterialSwitch;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EditEventAllBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Group addAttendeesGroup;

  @NonNull
  public final TextInputLayout addAttendeesRow;

  @NonNull
  public final RecipientEditTextView attendees;

  @NonNull
  public final ImageView attendeesIcon;

  @NonNull
  public final Spinner availability;

  @NonNull
  public final ImageView availabilityIcon;

  @NonNull
  public final View calendarSelectorGroupBackground;

  @NonNull
  public final ImageView calendarSelectorGroupIcon;

  @NonNull
  public final Spinner calendarsSpinner;

  @NonNull
  public final ImageButton changeColor;

  @NonNull
  public final EditText description;

  @NonNull
  public final ImageView descriptionIcon;

  @NonNull
  public final TextInputLayout descriptionRow;

  @NonNull
  public final ConstraintLayout editEventAll;

  @NonNull
  public final Button endDate;

  @NonNull
  public final TextView endDateHomeTz;

  @NonNull
  public final Button endTime;

  @NonNull
  public final TextView endTimeHomeTz;

  @NonNull
  public final LinearLayout fromRowHomeTz;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final MaterialSwitch isAllDay;

  @NonNull
  public final TextView isAllDayLabel;

  @NonNull
  public final AutoCompleteTextView location;

  @NonNull
  public final TextView organizer;

  @NonNull
  public final TextView organizerLabel;

  @NonNull
  public final LinearLayout organizerRow;

  @NonNull
  public final Button reminderAdd;

  @NonNull
  public final ImageView reminderIcon;

  @NonNull
  public final LinearLayout reminderItemsContainer;

  @NonNull
  public final Group responseGroup;

  @NonNull
  public final TextView responseLabel;

  @NonNull
  public final RadioButton responseMaybe;

  @NonNull
  public final RadioButton responseNo;

  @NonNull
  public final LinearLayout responseRow;

  @NonNull
  public final RadioGroup responseValue;

  @NonNull
  public final RadioButton responseYes;

  @NonNull
  public final Button rrule;

  @NonNull
  public final ImageView rruleIcon;

  @NonNull
  public final Button startDate;

  @NonNull
  public final TextView startDateHomeTz;

  @NonNull
  public final Button startTime;

  @NonNull
  public final TextView startTimeHomeTz;

  @NonNull
  public final Button timezoneButton;

  @NonNull
  public final Group timezoneButtonRow;

  @NonNull
  public final ImageView timezoneIcon;

  @NonNull
  public final TextView timezoneTextView;

  @NonNull
  public final LinearLayout timezoneTextviewRow;

  @NonNull
  public final TextInputEditText title;

  @NonNull
  public final LinearLayout toRowHomeTz;

  @NonNull
  public final EditText url;

  @NonNull
  public final ImageView urlIcon;

  @NonNull
  public final TextInputLayout urlRow;

  @NonNull
  public final View view;

  @NonNull
  public final View view1;

  @NonNull
  public final View view2;

  @NonNull
  public final View view3;

  @NonNull
  public final View view4;

  @NonNull
  public final View view5;

  @NonNull
  public final View view6;

  @NonNull
  public final View view7;

  @NonNull
  public final Spinner visibility;

  @NonNull
  public final ImageView visibilityIcon;

  @NonNull
  public final TextView when;

  @NonNull
  public final TextView whenLabel;

  @NonNull
  public final LinearLayout whenRow;

  @NonNull
  public final ImageView whereIcon;

  @NonNull
  public final TextInputLayout whereRow;

  private EditEventAllBinding(@NonNull LinearLayout rootView, @NonNull Group addAttendeesGroup,
      @NonNull TextInputLayout addAttendeesRow, @NonNull RecipientEditTextView attendees,
      @NonNull ImageView attendeesIcon, @NonNull Spinner availability,
      @NonNull ImageView availabilityIcon, @NonNull View calendarSelectorGroupBackground,
      @NonNull ImageView calendarSelectorGroupIcon, @NonNull Spinner calendarsSpinner,
      @NonNull ImageButton changeColor, @NonNull EditText description,
      @NonNull ImageView descriptionIcon, @NonNull TextInputLayout descriptionRow,
      @NonNull ConstraintLayout editEventAll, @NonNull Button endDate,
      @NonNull TextView endDateHomeTz, @NonNull Button endTime, @NonNull TextView endTimeHomeTz,
      @NonNull LinearLayout fromRowHomeTz, @NonNull ImageView imageView,
      @NonNull MaterialSwitch isAllDay, @NonNull TextView isAllDayLabel,
      @NonNull AutoCompleteTextView location, @NonNull TextView organizer,
      @NonNull TextView organizerLabel, @NonNull LinearLayout organizerRow,
      @NonNull Button reminderAdd, @NonNull ImageView reminderIcon,
      @NonNull LinearLayout reminderItemsContainer, @NonNull Group responseGroup,
      @NonNull TextView responseLabel, @NonNull RadioButton responseMaybe,
      @NonNull RadioButton responseNo, @NonNull LinearLayout responseRow,
      @NonNull RadioGroup responseValue, @NonNull RadioButton responseYes, @NonNull Button rrule,
      @NonNull ImageView rruleIcon, @NonNull Button startDate, @NonNull TextView startDateHomeTz,
      @NonNull Button startTime, @NonNull TextView startTimeHomeTz, @NonNull Button timezoneButton,
      @NonNull Group timezoneButtonRow, @NonNull ImageView timezoneIcon,
      @NonNull TextView timezoneTextView, @NonNull LinearLayout timezoneTextviewRow,
      @NonNull TextInputEditText title, @NonNull LinearLayout toRowHomeTz, @NonNull EditText url,
      @NonNull ImageView urlIcon, @NonNull TextInputLayout urlRow, @NonNull View view,
      @NonNull View view1, @NonNull View view2, @NonNull View view3, @NonNull View view4,
      @NonNull View view5, @NonNull View view6, @NonNull View view7, @NonNull Spinner visibility,
      @NonNull ImageView visibilityIcon, @NonNull TextView when, @NonNull TextView whenLabel,
      @NonNull LinearLayout whenRow, @NonNull ImageView whereIcon,
      @NonNull TextInputLayout whereRow) {
    this.rootView = rootView;
    this.addAttendeesGroup = addAttendeesGroup;
    this.addAttendeesRow = addAttendeesRow;
    this.attendees = attendees;
    this.attendeesIcon = attendeesIcon;
    this.availability = availability;
    this.availabilityIcon = availabilityIcon;
    this.calendarSelectorGroupBackground = calendarSelectorGroupBackground;
    this.calendarSelectorGroupIcon = calendarSelectorGroupIcon;
    this.calendarsSpinner = calendarsSpinner;
    this.changeColor = changeColor;
    this.description = description;
    this.descriptionIcon = descriptionIcon;
    this.descriptionRow = descriptionRow;
    this.editEventAll = editEventAll;
    this.endDate = endDate;
    this.endDateHomeTz = endDateHomeTz;
    this.endTime = endTime;
    this.endTimeHomeTz = endTimeHomeTz;
    this.fromRowHomeTz = fromRowHomeTz;
    this.imageView = imageView;
    this.isAllDay = isAllDay;
    this.isAllDayLabel = isAllDayLabel;
    this.location = location;
    this.organizer = organizer;
    this.organizerLabel = organizerLabel;
    this.organizerRow = organizerRow;
    this.reminderAdd = reminderAdd;
    this.reminderIcon = reminderIcon;
    this.reminderItemsContainer = reminderItemsContainer;
    this.responseGroup = responseGroup;
    this.responseLabel = responseLabel;
    this.responseMaybe = responseMaybe;
    this.responseNo = responseNo;
    this.responseRow = responseRow;
    this.responseValue = responseValue;
    this.responseYes = responseYes;
    this.rrule = rrule;
    this.rruleIcon = rruleIcon;
    this.startDate = startDate;
    this.startDateHomeTz = startDateHomeTz;
    this.startTime = startTime;
    this.startTimeHomeTz = startTimeHomeTz;
    this.timezoneButton = timezoneButton;
    this.timezoneButtonRow = timezoneButtonRow;
    this.timezoneIcon = timezoneIcon;
    this.timezoneTextView = timezoneTextView;
    this.timezoneTextviewRow = timezoneTextviewRow;
    this.title = title;
    this.toRowHomeTz = toRowHomeTz;
    this.url = url;
    this.urlIcon = urlIcon;
    this.urlRow = urlRow;
    this.view = view;
    this.view1 = view1;
    this.view2 = view2;
    this.view3 = view3;
    this.view4 = view4;
    this.view5 = view5;
    this.view6 = view6;
    this.view7 = view7;
    this.visibility = visibility;
    this.visibilityIcon = visibilityIcon;
    this.when = when;
    this.whenLabel = whenLabel;
    this.whenRow = whenRow;
    this.whereIcon = whereIcon;
    this.whereRow = whereRow;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EditEventAllBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EditEventAllBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.edit_event_all, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EditEventAllBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add_attendees_group;
      Group addAttendeesGroup = ViewBindings.findChildViewById(rootView, id);
      if (addAttendeesGroup == null) {
        break missingId;
      }

      id = R.id.add_attendees_row;
      TextInputLayout addAttendeesRow = ViewBindings.findChildViewById(rootView, id);
      if (addAttendeesRow == null) {
        break missingId;
      }

      id = R.id.attendees;
      RecipientEditTextView attendees = ViewBindings.findChildViewById(rootView, id);
      if (attendees == null) {
        break missingId;
      }

      id = R.id.attendees_icon;
      ImageView attendeesIcon = ViewBindings.findChildViewById(rootView, id);
      if (attendeesIcon == null) {
        break missingId;
      }

      id = R.id.availability;
      Spinner availability = ViewBindings.findChildViewById(rootView, id);
      if (availability == null) {
        break missingId;
      }

      id = R.id.availability_icon;
      ImageView availabilityIcon = ViewBindings.findChildViewById(rootView, id);
      if (availabilityIcon == null) {
        break missingId;
      }

      id = R.id.calendar_selector_group_background;
      View calendarSelectorGroupBackground = ViewBindings.findChildViewById(rootView, id);
      if (calendarSelectorGroupBackground == null) {
        break missingId;
      }

      id = R.id.calendar_selector_group_icon;
      ImageView calendarSelectorGroupIcon = ViewBindings.findChildViewById(rootView, id);
      if (calendarSelectorGroupIcon == null) {
        break missingId;
      }

      id = R.id.calendars_spinner;
      Spinner calendarsSpinner = ViewBindings.findChildViewById(rootView, id);
      if (calendarsSpinner == null) {
        break missingId;
      }

      id = R.id.change_color;
      ImageButton changeColor = ViewBindings.findChildViewById(rootView, id);
      if (changeColor == null) {
        break missingId;
      }

      id = R.id.description;
      EditText description = ViewBindings.findChildViewById(rootView, id);
      if (description == null) {
        break missingId;
      }

      id = R.id.description_icon;
      ImageView descriptionIcon = ViewBindings.findChildViewById(rootView, id);
      if (descriptionIcon == null) {
        break missingId;
      }

      id = R.id.description_row;
      TextInputLayout descriptionRow = ViewBindings.findChildViewById(rootView, id);
      if (descriptionRow == null) {
        break missingId;
      }

      id = R.id.edit_event_all;
      ConstraintLayout editEventAll = ViewBindings.findChildViewById(rootView, id);
      if (editEventAll == null) {
        break missingId;
      }

      id = R.id.end_date;
      Button endDate = ViewBindings.findChildViewById(rootView, id);
      if (endDate == null) {
        break missingId;
      }

      id = R.id.end_date_home_tz;
      TextView endDateHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (endDateHomeTz == null) {
        break missingId;
      }

      id = R.id.end_time;
      Button endTime = ViewBindings.findChildViewById(rootView, id);
      if (endTime == null) {
        break missingId;
      }

      id = R.id.end_time_home_tz;
      TextView endTimeHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (endTimeHomeTz == null) {
        break missingId;
      }

      id = R.id.from_row_home_tz;
      LinearLayout fromRowHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (fromRowHomeTz == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.is_all_day;
      MaterialSwitch isAllDay = ViewBindings.findChildViewById(rootView, id);
      if (isAllDay == null) {
        break missingId;
      }

      id = R.id.is_all_day_label;
      TextView isAllDayLabel = ViewBindings.findChildViewById(rootView, id);
      if (isAllDayLabel == null) {
        break missingId;
      }

      id = R.id.location;
      AutoCompleteTextView location = ViewBindings.findChildViewById(rootView, id);
      if (location == null) {
        break missingId;
      }

      id = R.id.organizer;
      TextView organizer = ViewBindings.findChildViewById(rootView, id);
      if (organizer == null) {
        break missingId;
      }

      id = R.id.organizer_label;
      TextView organizerLabel = ViewBindings.findChildViewById(rootView, id);
      if (organizerLabel == null) {
        break missingId;
      }

      id = R.id.organizer_row;
      LinearLayout organizerRow = ViewBindings.findChildViewById(rootView, id);
      if (organizerRow == null) {
        break missingId;
      }

      id = R.id.reminder_add;
      Button reminderAdd = ViewBindings.findChildViewById(rootView, id);
      if (reminderAdd == null) {
        break missingId;
      }

      id = R.id.reminder_icon;
      ImageView reminderIcon = ViewBindings.findChildViewById(rootView, id);
      if (reminderIcon == null) {
        break missingId;
      }

      id = R.id.reminder_items_container;
      LinearLayout reminderItemsContainer = ViewBindings.findChildViewById(rootView, id);
      if (reminderItemsContainer == null) {
        break missingId;
      }

      id = R.id.response_group;
      Group responseGroup = ViewBindings.findChildViewById(rootView, id);
      if (responseGroup == null) {
        break missingId;
      }

      id = R.id.response_label;
      TextView responseLabel = ViewBindings.findChildViewById(rootView, id);
      if (responseLabel == null) {
        break missingId;
      }

      id = R.id.response_maybe;
      RadioButton responseMaybe = ViewBindings.findChildViewById(rootView, id);
      if (responseMaybe == null) {
        break missingId;
      }

      id = R.id.response_no;
      RadioButton responseNo = ViewBindings.findChildViewById(rootView, id);
      if (responseNo == null) {
        break missingId;
      }

      id = R.id.response_row;
      LinearLayout responseRow = ViewBindings.findChildViewById(rootView, id);
      if (responseRow == null) {
        break missingId;
      }

      id = R.id.response_value;
      RadioGroup responseValue = ViewBindings.findChildViewById(rootView, id);
      if (responseValue == null) {
        break missingId;
      }

      id = R.id.response_yes;
      RadioButton responseYes = ViewBindings.findChildViewById(rootView, id);
      if (responseYes == null) {
        break missingId;
      }

      id = R.id.rrule;
      Button rrule = ViewBindings.findChildViewById(rootView, id);
      if (rrule == null) {
        break missingId;
      }

      id = R.id.rrule_icon;
      ImageView rruleIcon = ViewBindings.findChildViewById(rootView, id);
      if (rruleIcon == null) {
        break missingId;
      }

      id = R.id.start_date;
      Button startDate = ViewBindings.findChildViewById(rootView, id);
      if (startDate == null) {
        break missingId;
      }

      id = R.id.start_date_home_tz;
      TextView startDateHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (startDateHomeTz == null) {
        break missingId;
      }

      id = R.id.start_time;
      Button startTime = ViewBindings.findChildViewById(rootView, id);
      if (startTime == null) {
        break missingId;
      }

      id = R.id.start_time_home_tz;
      TextView startTimeHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (startTimeHomeTz == null) {
        break missingId;
      }

      id = R.id.timezone_button;
      Button timezoneButton = ViewBindings.findChildViewById(rootView, id);
      if (timezoneButton == null) {
        break missingId;
      }

      id = R.id.timezone_button_row;
      Group timezoneButtonRow = ViewBindings.findChildViewById(rootView, id);
      if (timezoneButtonRow == null) {
        break missingId;
      }

      id = R.id.timezone_icon;
      ImageView timezoneIcon = ViewBindings.findChildViewById(rootView, id);
      if (timezoneIcon == null) {
        break missingId;
      }

      id = R.id.timezone_textView;
      TextView timezoneTextView = ViewBindings.findChildViewById(rootView, id);
      if (timezoneTextView == null) {
        break missingId;
      }

      id = R.id.timezone_textview_row;
      LinearLayout timezoneTextviewRow = ViewBindings.findChildViewById(rootView, id);
      if (timezoneTextviewRow == null) {
        break missingId;
      }

      id = R.id.title;
      TextInputEditText title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.to_row_home_tz;
      LinearLayout toRowHomeTz = ViewBindings.findChildViewById(rootView, id);
      if (toRowHomeTz == null) {
        break missingId;
      }

      id = R.id.url;
      EditText url = ViewBindings.findChildViewById(rootView, id);
      if (url == null) {
        break missingId;
      }

      id = R.id.url_icon;
      ImageView urlIcon = ViewBindings.findChildViewById(rootView, id);
      if (urlIcon == null) {
        break missingId;
      }

      id = R.id.url_row;
      TextInputLayout urlRow = ViewBindings.findChildViewById(rootView, id);
      if (urlRow == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      id = R.id.view1;
      View view1 = ViewBindings.findChildViewById(rootView, id);
      if (view1 == null) {
        break missingId;
      }

      id = R.id.view2;
      View view2 = ViewBindings.findChildViewById(rootView, id);
      if (view2 == null) {
        break missingId;
      }

      id = R.id.view3;
      View view3 = ViewBindings.findChildViewById(rootView, id);
      if (view3 == null) {
        break missingId;
      }

      id = R.id.view4;
      View view4 = ViewBindings.findChildViewById(rootView, id);
      if (view4 == null) {
        break missingId;
      }

      id = R.id.view5;
      View view5 = ViewBindings.findChildViewById(rootView, id);
      if (view5 == null) {
        break missingId;
      }

      id = R.id.view6;
      View view6 = ViewBindings.findChildViewById(rootView, id);
      if (view6 == null) {
        break missingId;
      }

      id = R.id.view7;
      View view7 = ViewBindings.findChildViewById(rootView, id);
      if (view7 == null) {
        break missingId;
      }

      id = R.id.visibility;
      Spinner visibility = ViewBindings.findChildViewById(rootView, id);
      if (visibility == null) {
        break missingId;
      }

      id = R.id.visibility_icon;
      ImageView visibilityIcon = ViewBindings.findChildViewById(rootView, id);
      if (visibilityIcon == null) {
        break missingId;
      }

      id = R.id.when;
      TextView when = ViewBindings.findChildViewById(rootView, id);
      if (when == null) {
        break missingId;
      }

      id = R.id.when_label;
      TextView whenLabel = ViewBindings.findChildViewById(rootView, id);
      if (whenLabel == null) {
        break missingId;
      }

      id = R.id.when_row;
      LinearLayout whenRow = ViewBindings.findChildViewById(rootView, id);
      if (whenRow == null) {
        break missingId;
      }

      id = R.id.where_icon;
      ImageView whereIcon = ViewBindings.findChildViewById(rootView, id);
      if (whereIcon == null) {
        break missingId;
      }

      id = R.id.where_row;
      TextInputLayout whereRow = ViewBindings.findChildViewById(rootView, id);
      if (whereRow == null) {
        break missingId;
      }

      return new EditEventAllBinding((LinearLayout) rootView, addAttendeesGroup, addAttendeesRow,
          attendees, attendeesIcon, availability, availabilityIcon, calendarSelectorGroupBackground,
          calendarSelectorGroupIcon, calendarsSpinner, changeColor, description, descriptionIcon,
          descriptionRow, editEventAll, endDate, endDateHomeTz, endTime, endTimeHomeTz,
          fromRowHomeTz, imageView, isAllDay, isAllDayLabel, location, organizer, organizerLabel,
          organizerRow, reminderAdd, reminderIcon, reminderItemsContainer, responseGroup,
          responseLabel, responseMaybe, responseNo, responseRow, responseValue, responseYes, rrule,
          rruleIcon, startDate, startDateHomeTz, startTime, startTimeHomeTz, timezoneButton,
          timezoneButtonRow, timezoneIcon, timezoneTextView, timezoneTextviewRow, title,
          toRowHomeTz, url, urlIcon, urlRow, view, view1, view2, view3, view4, view5, view6, view7,
          visibility, visibilityIcon, when, whenLabel, whenRow, whereIcon, whereRow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
