// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.event.AttendeesView;
import com.google.android.material.appbar.AppBarLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EventInfoBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final AppBarLayout bar;

  @NonNull
  public final LinearLayout calendarContainer;

  @NonNull
  public final TextView calendarLabel;

  @NonNull
  public final TextView calendarName;

  @NonNull
  public final ExpandableTextviewBinding description;

  @NonNull
  public final Button emailAttendeesButton;

  @NonNull
  public final LinearLayout emailAttendeesContainer;

  @NonNull
  public final TextView eventInfoErrorMsg;

  @NonNull
  public final RelativeLayout eventInfoLoadingMsg;

  @NonNull
  public final ProgressBar eventInfoProgressBar;

  @NonNull
  public final ScrollView eventInfoScrollView;

  @NonNull
  public final Button launchCustomAppButton;

  @NonNull
  public final LinearLayout launchCustomAppContainer;

  @NonNull
  public final AttendeesView longAttendeeList;

  @NonNull
  public final TextView organizer;

  @NonNull
  public final LinearLayout organizerContainer;

  @NonNull
  public final TextView organizerLabel;

  @NonNull
  public final Button reminderAdd;

  @NonNull
  public final LinearLayout reminderItemsContainer;

  @NonNull
  public final LinearLayout responseContainer;

  @NonNull
  public final TextView responseLabel;

  @NonNull
  public final RadioButton responseMaybe;

  @NonNull
  public final RadioButton responseNo;

  @NonNull
  public final RadioGroup responseValue;

  @NonNull
  public final RadioButton responseYes;

  @NonNull
  public final ExpandableTextviewBinding url;

  private EventInfoBinding(@NonNull FrameLayout rootView, @NonNull AppBarLayout bar,
      @NonNull LinearLayout calendarContainer, @NonNull TextView calendarLabel,
      @NonNull TextView calendarName, @NonNull ExpandableTextviewBinding description,
      @NonNull Button emailAttendeesButton, @NonNull LinearLayout emailAttendeesContainer,
      @NonNull TextView eventInfoErrorMsg, @NonNull RelativeLayout eventInfoLoadingMsg,
      @NonNull ProgressBar eventInfoProgressBar, @NonNull ScrollView eventInfoScrollView,
      @NonNull Button launchCustomAppButton, @NonNull LinearLayout launchCustomAppContainer,
      @NonNull AttendeesView longAttendeeList, @NonNull TextView organizer,
      @NonNull LinearLayout organizerContainer, @NonNull TextView organizerLabel,
      @NonNull Button reminderAdd, @NonNull LinearLayout reminderItemsContainer,
      @NonNull LinearLayout responseContainer, @NonNull TextView responseLabel,
      @NonNull RadioButton responseMaybe, @NonNull RadioButton responseNo,
      @NonNull RadioGroup responseValue, @NonNull RadioButton responseYes,
      @NonNull ExpandableTextviewBinding url) {
    this.rootView = rootView;
    this.bar = bar;
    this.calendarContainer = calendarContainer;
    this.calendarLabel = calendarLabel;
    this.calendarName = calendarName;
    this.description = description;
    this.emailAttendeesButton = emailAttendeesButton;
    this.emailAttendeesContainer = emailAttendeesContainer;
    this.eventInfoErrorMsg = eventInfoErrorMsg;
    this.eventInfoLoadingMsg = eventInfoLoadingMsg;
    this.eventInfoProgressBar = eventInfoProgressBar;
    this.eventInfoScrollView = eventInfoScrollView;
    this.launchCustomAppButton = launchCustomAppButton;
    this.launchCustomAppContainer = launchCustomAppContainer;
    this.longAttendeeList = longAttendeeList;
    this.organizer = organizer;
    this.organizerContainer = organizerContainer;
    this.organizerLabel = organizerLabel;
    this.reminderAdd = reminderAdd;
    this.reminderItemsContainer = reminderItemsContainer;
    this.responseContainer = responseContainer;
    this.responseLabel = responseLabel;
    this.responseMaybe = responseMaybe;
    this.responseNo = responseNo;
    this.responseValue = responseValue;
    this.responseYes = responseYes;
    this.url = url;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EventInfoBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EventInfoBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.event_info, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EventInfoBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bar;
      AppBarLayout bar = ViewBindings.findChildViewById(rootView, id);
      if (bar == null) {
        break missingId;
      }

      id = R.id.calendar_container;
      LinearLayout calendarContainer = ViewBindings.findChildViewById(rootView, id);
      if (calendarContainer == null) {
        break missingId;
      }

      id = R.id.calendar_label;
      TextView calendarLabel = ViewBindings.findChildViewById(rootView, id);
      if (calendarLabel == null) {
        break missingId;
      }

      id = R.id.calendar_name;
      TextView calendarName = ViewBindings.findChildViewById(rootView, id);
      if (calendarName == null) {
        break missingId;
      }

      id = R.id.description;
      View description = ViewBindings.findChildViewById(rootView, id);
      if (description == null) {
        break missingId;
      }
      ExpandableTextviewBinding binding_description = ExpandableTextviewBinding.bind(description);

      id = R.id.email_attendees_button;
      Button emailAttendeesButton = ViewBindings.findChildViewById(rootView, id);
      if (emailAttendeesButton == null) {
        break missingId;
      }

      id = R.id.email_attendees_container;
      LinearLayout emailAttendeesContainer = ViewBindings.findChildViewById(rootView, id);
      if (emailAttendeesContainer == null) {
        break missingId;
      }

      id = R.id.event_info_error_msg;
      TextView eventInfoErrorMsg = ViewBindings.findChildViewById(rootView, id);
      if (eventInfoErrorMsg == null) {
        break missingId;
      }

      id = R.id.event_info_loading_msg;
      RelativeLayout eventInfoLoadingMsg = ViewBindings.findChildViewById(rootView, id);
      if (eventInfoLoadingMsg == null) {
        break missingId;
      }

      id = R.id.event_info_progress_bar;
      ProgressBar eventInfoProgressBar = ViewBindings.findChildViewById(rootView, id);
      if (eventInfoProgressBar == null) {
        break missingId;
      }

      id = R.id.event_info_scroll_view;
      ScrollView eventInfoScrollView = ViewBindings.findChildViewById(rootView, id);
      if (eventInfoScrollView == null) {
        break missingId;
      }

      id = R.id.launch_custom_app_button;
      Button launchCustomAppButton = ViewBindings.findChildViewById(rootView, id);
      if (launchCustomAppButton == null) {
        break missingId;
      }

      id = R.id.launch_custom_app_container;
      LinearLayout launchCustomAppContainer = ViewBindings.findChildViewById(rootView, id);
      if (launchCustomAppContainer == null) {
        break missingId;
      }

      id = R.id.long_attendee_list;
      AttendeesView longAttendeeList = ViewBindings.findChildViewById(rootView, id);
      if (longAttendeeList == null) {
        break missingId;
      }

      id = R.id.organizer;
      TextView organizer = ViewBindings.findChildViewById(rootView, id);
      if (organizer == null) {
        break missingId;
      }

      id = R.id.organizer_container;
      LinearLayout organizerContainer = ViewBindings.findChildViewById(rootView, id);
      if (organizerContainer == null) {
        break missingId;
      }

      id = R.id.organizer_label;
      TextView organizerLabel = ViewBindings.findChildViewById(rootView, id);
      if (organizerLabel == null) {
        break missingId;
      }

      id = R.id.reminder_add;
      Button reminderAdd = ViewBindings.findChildViewById(rootView, id);
      if (reminderAdd == null) {
        break missingId;
      }

      id = R.id.reminder_items_container;
      LinearLayout reminderItemsContainer = ViewBindings.findChildViewById(rootView, id);
      if (reminderItemsContainer == null) {
        break missingId;
      }

      id = R.id.response_container;
      LinearLayout responseContainer = ViewBindings.findChildViewById(rootView, id);
      if (responseContainer == null) {
        break missingId;
      }

      id = R.id.response_label;
      TextView responseLabel = ViewBindings.findChildViewById(rootView, id);
      if (responseLabel == null) {
        break missingId;
      }

      id = R.id.response_maybe;
      RadioButton responseMaybe = ViewBindings.findChildViewById(rootView, id);
      if (responseMaybe == null) {
        break missingId;
      }

      id = R.id.response_no;
      RadioButton responseNo = ViewBindings.findChildViewById(rootView, id);
      if (responseNo == null) {
        break missingId;
      }

      id = R.id.response_value;
      RadioGroup responseValue = ViewBindings.findChildViewById(rootView, id);
      if (responseValue == null) {
        break missingId;
      }

      id = R.id.response_yes;
      RadioButton responseYes = ViewBindings.findChildViewById(rootView, id);
      if (responseYes == null) {
        break missingId;
      }

      id = R.id.url;
      View url = ViewBindings.findChildViewById(rootView, id);
      if (url == null) {
        break missingId;
      }
      ExpandableTextviewBinding binding_url = ExpandableTextviewBinding.bind(url);

      return new EventInfoBinding((FrameLayout) rootView, bar, calendarContainer, calendarLabel,
          calendarName, binding_description, emailAttendeesButton, emailAttendeesContainer,
          eventInfoErrorMsg, eventInfoLoadingMsg, eventInfoProgressBar, eventInfoScrollView,
          launchCustomAppButton, launchCustomAppContainer, longAttendeeList, organizer,
          organizerContainer, organizerLabel, reminderAdd, reminderItemsContainer,
          responseContainer, responseLabel, responseMaybe, responseNo, responseValue, responseYes,
          binding_url);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
