// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EventInfoHeadlineBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button changeColor;

  @NonNull
  public final Button delete;

  @NonNull
  public final Button edit;

  @NonNull
  public final LinearLayout eventInfoButtonsContainer;

  @NonNull
  public final LinearLayout eventInfoHeadline;

  @NonNull
  public final TextView title;

  @NonNull
  public final TextView whenDatetime;

  @NonNull
  public final TextView whenRepeat;

  @NonNull
  public final TextView where;

  private EventInfoHeadlineBinding(@NonNull LinearLayout rootView, @NonNull Button changeColor,
      @NonNull Button delete, @NonNull Button edit, @NonNull LinearLayout eventInfoButtonsContainer,
      @NonNull LinearLayout eventInfoHeadline, @NonNull TextView title,
      @NonNull TextView whenDatetime, @NonNull TextView whenRepeat, @NonNull TextView where) {
    this.rootView = rootView;
    this.changeColor = changeColor;
    this.delete = delete;
    this.edit = edit;
    this.eventInfoButtonsContainer = eventInfoButtonsContainer;
    this.eventInfoHeadline = eventInfoHeadline;
    this.title = title;
    this.whenDatetime = whenDatetime;
    this.whenRepeat = whenRepeat;
    this.where = where;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EventInfoHeadlineBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EventInfoHeadlineBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.event_info_headline, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EventInfoHeadlineBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.change_color;
      Button changeColor = ViewBindings.findChildViewById(rootView, id);
      if (changeColor == null) {
        break missingId;
      }

      id = R.id.delete;
      Button delete = ViewBindings.findChildViewById(rootView, id);
      if (delete == null) {
        break missingId;
      }

      id = R.id.edit;
      Button edit = ViewBindings.findChildViewById(rootView, id);
      if (edit == null) {
        break missingId;
      }

      id = R.id.event_info_buttons_container;
      LinearLayout eventInfoButtonsContainer = ViewBindings.findChildViewById(rootView, id);
      if (eventInfoButtonsContainer == null) {
        break missingId;
      }

      LinearLayout eventInfoHeadline = (LinearLayout) rootView;

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.when_datetime;
      TextView whenDatetime = ViewBindings.findChildViewById(rootView, id);
      if (whenDatetime == null) {
        break missingId;
      }

      id = R.id.when_repeat;
      TextView whenRepeat = ViewBindings.findChildViewById(rootView, id);
      if (whenRepeat == null) {
        break missingId;
      }

      id = R.id.where;
      TextView where = ViewBindings.findChildViewById(rootView, id);
      if (where == null) {
        break missingId;
      }

      return new EventInfoHeadlineBinding((LinearLayout) rootView, changeColor, delete, edit,
          eventInfoButtonsContainer, eventInfoHeadline, title, whenDatetime, whenRepeat, where);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
