// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.ExpandableTextView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class ExpandableTextviewBinding implements ViewBinding {
  @NonNull
  private final ExpandableTextView rootView;

  @NonNull
  public final ImageButton expandCollapse;

  @NonNull
  public final TextView expandableText;

  private ExpandableTextviewBinding(@NonNull ExpandableTextView rootView,
      @NonNull ImageButton expandCollapse, @NonNull TextView expandableText) {
    this.rootView = rootView;
    this.expandCollapse = expandCollapse;
    this.expandableText = expandableText;
  }

  @Override
  @NonNull
  public ExpandableTextView getRoot() {
    return rootView;
  }

  @NonNull
  public static ExpandableTextviewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ExpandableTextviewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.expandable_textview, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ExpandableTextviewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.expand_collapse;
      ImageButton expandCollapse = ViewBindings.findChildViewById(rootView, id);
      if (expandCollapse == null) {
        break missingId;
      }

      id = R.id.expandable_text;
      TextView expandableText = ViewBindings.findChildViewById(rootView, id);
      if (expandableText == null) {
        break missingId;
      }

      return new ExpandableTextviewBinding((ExpandableTextView) rootView, expandCollapse,
          expandableText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
