// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class FullMonthHeaderBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView d0Label;

  @NonNull
  public final TextView d1Label;

  @NonNull
  public final TextView d2Label;

  @NonNull
  public final TextView d3Label;

  @NonNull
  public final TextView d4Label;

  @NonNull
  public final TextView d5Label;

  @NonNull
  public final TextView d6Label;

  @NonNull
  public final TextView wkLabel;

  private FullMonthHeaderBinding(@NonNull LinearLayout rootView, @NonNull TextView d0Label,
      @NonNull TextView d1Label, @NonNull TextView d2Label, @NonNull TextView d3Label,
      @NonNull TextView d4Label, @NonNull TextView d5Label, @NonNull TextView d6Label,
      @NonNull TextView wkLabel) {
    this.rootView = rootView;
    this.d0Label = d0Label;
    this.d1Label = d1Label;
    this.d2Label = d2Label;
    this.d3Label = d3Label;
    this.d4Label = d4Label;
    this.d5Label = d5Label;
    this.d6Label = d6Label;
    this.wkLabel = wkLabel;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FullMonthHeaderBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FullMonthHeaderBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.full_month_header, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FullMonthHeaderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.d0_label;
      TextView d0Label = ViewBindings.findChildViewById(rootView, id);
      if (d0Label == null) {
        break missingId;
      }

      id = R.id.d1_label;
      TextView d1Label = ViewBindings.findChildViewById(rootView, id);
      if (d1Label == null) {
        break missingId;
      }

      id = R.id.d2_label;
      TextView d2Label = ViewBindings.findChildViewById(rootView, id);
      if (d2Label == null) {
        break missingId;
      }

      id = R.id.d3_label;
      TextView d3Label = ViewBindings.findChildViewById(rootView, id);
      if (d3Label == null) {
        break missingId;
      }

      id = R.id.d4_label;
      TextView d4Label = ViewBindings.findChildViewById(rootView, id);
      if (d4Label == null) {
        break missingId;
      }

      id = R.id.d5_label;
      TextView d5Label = ViewBindings.findChildViewById(rootView, id);
      if (d5Label == null) {
        break missingId;
      }

      id = R.id.d6_label;
      TextView d6Label = ViewBindings.findChildViewById(rootView, id);
      if (d6Label == null) {
        break missingId;
      }

      id = R.id.wk_label;
      TextView wkLabel = ViewBindings.findChildViewById(rootView, id);
      if (wkLabel == null) {
        break missingId;
      }

      return new FullMonthHeaderBinding((LinearLayout) rootView, d0Label, d1Label, d2Label, d3Label,
          d4Label, d5Label, d6Label, wkLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
