// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.imageview.ShapeableImageView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class LocationDropdownItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ShapeableImageView icon;

  @NonNull
  public final TextView locationAddress;

  @NonNull
  public final TextView locationName;

  private LocationDropdownItemBinding(@NonNull LinearLayout rootView,
      @NonNull ShapeableImageView icon, @NonNull TextView locationAddress,
      @NonNull TextView locationName) {
    this.rootView = rootView;
    this.icon = icon;
    this.locationAddress = locationAddress;
    this.locationName = locationName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LocationDropdownItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LocationDropdownItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.location_dropdown_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LocationDropdownItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.icon;
      ShapeableImageView icon = ViewBindings.findChildViewById(rootView, id);
      if (icon == null) {
        break missingId;
      }

      id = R.id.location_address;
      TextView locationAddress = ViewBindings.findChildViewById(rootView, id);
      if (locationAddress == null) {
        break missingId;
      }

      id = R.id.location_name;
      TextView locationName = ViewBindings.findChildViewById(rootView, id);
      if (locationName == null) {
        break missingId;
      }

      return new LocationDropdownItemBinding((LinearLayout) rootView, icon, locationAddress,
          locationName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
