// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.selectcalendars.CalendarColorSquare;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class MiniCalendarItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView calendar;

  @NonNull
  public final CalendarColorSquare color;

  @NonNull
  public final TextView status;

  @NonNull
  public final CheckBox visibleCheckBox;

  private MiniCalendarItemBinding(@NonNull ConstraintLayout rootView, @NonNull TextView calendar,
      @NonNull CalendarColorSquare color, @NonNull TextView status,
      @NonNull CheckBox visibleCheckBox) {
    this.rootView = rootView;
    this.calendar = calendar;
    this.color = color;
    this.status = status;
    this.visibleCheckBox = visibleCheckBox;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static MiniCalendarItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MiniCalendarItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.mini_calendar_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MiniCalendarItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.calendar;
      TextView calendar = ViewBindings.findChildViewById(rootView, id);
      if (calendar == null) {
        break missingId;
      }

      id = R.id.color;
      CalendarColorSquare color = ViewBindings.findChildViewById(rootView, id);
      if (color == null) {
        break missingId;
      }

      id = R.id.status;
      TextView status = ViewBindings.findChildViewById(rootView, id);
      if (status == null) {
        break missingId;
      }

      id = R.id.visible_check_box;
      CheckBox visibleCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (visibleCheckBox == null) {
        break missingId;
      }

      return new MiniCalendarItemBinding((ConstraintLayout) rootView, calendar, color, status,
          visibleCheckBox);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
