// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.month.MonthListView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class MonthByWeekBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final MiniMonthHeaderBinding dayNames;

  @NonNull
  public final MonthListView list;

  @NonNull
  public final LinearLayout month;

  @NonNull
  public final TextView monthName;

  private MonthByWeekBinding(@NonNull CardView rootView, @NonNull MiniMonthHeaderBinding dayNames,
      @NonNull MonthListView list, @NonNull LinearLayout month, @NonNull TextView monthName) {
    this.rootView = rootView;
    this.dayNames = dayNames;
    this.list = list;
    this.month = month;
    this.monthName = monthName;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static MonthByWeekBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MonthByWeekBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.month_by_week, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MonthByWeekBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.day_names;
      View dayNames = ViewBindings.findChildViewById(rootView, id);
      if (dayNames == null) {
        break missingId;
      }
      MiniMonthHeaderBinding binding_dayNames = MiniMonthHeaderBinding.bind(dayNames);

      id = android.R.id.list;
      MonthListView list = ViewBindings.findChildViewById(rootView, id);
      if (list == null) {
        break missingId;
      }

      id = R.id.month;
      LinearLayout month = ViewBindings.findChildViewById(rootView, id);
      if (month == null) {
        break missingId;
      }

      id = R.id.month_name;
      TextView monthName = ViewBindings.findChildViewById(rootView, id);
      if (monthName == null) {
        break missingId;
      }

      return new MonthByWeekBinding((CardView) rootView, binding_dayNames, list, month, monthName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
