// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android.calendar.recurrencepicker.LinearLayoutWithMaxWidth;
import com.google.android.material.materialswitch.MaterialSwitch;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class RecurrencepickerBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button done;

  @NonNull
  public final EditText endCount;

  @NonNull
  public final TextView endDate;

  @NonNull
  public final LinearLayout endGroup;

  @NonNull
  public final Spinner endSpinner;

  @NonNull
  public final Spinner freqSpinner;

  @NonNull
  public final EditText interval;

  @NonNull
  public final LinearLayout intervalGroup;

  @NonNull
  public final TextView intervalPostText;

  @NonNull
  public final TextView intervalPreText;

  @NonNull
  public final RadioGroup monthGroup;

  @NonNull
  public final LinearLayout options;

  @NonNull
  public final TextView postEndCount;

  @NonNull
  public final RadioButton repeatMonthlyByNthDayOfMonth;

  @NonNull
  public final RadioButton repeatMonthlyByNthDayOfTheWeek;

  @NonNull
  public final MaterialSwitch repeatSwitch;

  @NonNull
  public final LinearLayoutWithMaxWidth weekGroup;

  @NonNull
  public final LinearLayoutWithMaxWidth weekGroup2;

  private RecurrencepickerBinding(@NonNull LinearLayout rootView, @NonNull Button done,
      @NonNull EditText endCount, @NonNull TextView endDate, @NonNull LinearLayout endGroup,
      @NonNull Spinner endSpinner, @NonNull Spinner freqSpinner, @NonNull EditText interval,
      @NonNull LinearLayout intervalGroup, @NonNull TextView intervalPostText,
      @NonNull TextView intervalPreText, @NonNull RadioGroup monthGroup,
      @NonNull LinearLayout options, @NonNull TextView postEndCount,
      @NonNull RadioButton repeatMonthlyByNthDayOfMonth,
      @NonNull RadioButton repeatMonthlyByNthDayOfTheWeek, @NonNull MaterialSwitch repeatSwitch,
      @NonNull LinearLayoutWithMaxWidth weekGroup, @NonNull LinearLayoutWithMaxWidth weekGroup2) {
    this.rootView = rootView;
    this.done = done;
    this.endCount = endCount;
    this.endDate = endDate;
    this.endGroup = endGroup;
    this.endSpinner = endSpinner;
    this.freqSpinner = freqSpinner;
    this.interval = interval;
    this.intervalGroup = intervalGroup;
    this.intervalPostText = intervalPostText;
    this.intervalPreText = intervalPreText;
    this.monthGroup = monthGroup;
    this.options = options;
    this.postEndCount = postEndCount;
    this.repeatMonthlyByNthDayOfMonth = repeatMonthlyByNthDayOfMonth;
    this.repeatMonthlyByNthDayOfTheWeek = repeatMonthlyByNthDayOfTheWeek;
    this.repeatSwitch = repeatSwitch;
    this.weekGroup = weekGroup;
    this.weekGroup2 = weekGroup2;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RecurrencepickerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecurrencepickerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.recurrencepicker, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecurrencepickerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.done;
      Button done = ViewBindings.findChildViewById(rootView, id);
      if (done == null) {
        break missingId;
      }

      id = R.id.endCount;
      EditText endCount = ViewBindings.findChildViewById(rootView, id);
      if (endCount == null) {
        break missingId;
      }

      id = R.id.endDate;
      TextView endDate = ViewBindings.findChildViewById(rootView, id);
      if (endDate == null) {
        break missingId;
      }

      id = R.id.endGroup;
      LinearLayout endGroup = ViewBindings.findChildViewById(rootView, id);
      if (endGroup == null) {
        break missingId;
      }

      id = R.id.endSpinner;
      Spinner endSpinner = ViewBindings.findChildViewById(rootView, id);
      if (endSpinner == null) {
        break missingId;
      }

      id = R.id.freqSpinner;
      Spinner freqSpinner = ViewBindings.findChildViewById(rootView, id);
      if (freqSpinner == null) {
        break missingId;
      }

      id = R.id.interval;
      EditText interval = ViewBindings.findChildViewById(rootView, id);
      if (interval == null) {
        break missingId;
      }

      id = R.id.intervalGroup;
      LinearLayout intervalGroup = ViewBindings.findChildViewById(rootView, id);
      if (intervalGroup == null) {
        break missingId;
      }

      id = R.id.intervalPostText;
      TextView intervalPostText = ViewBindings.findChildViewById(rootView, id);
      if (intervalPostText == null) {
        break missingId;
      }

      id = R.id.intervalPreText;
      TextView intervalPreText = ViewBindings.findChildViewById(rootView, id);
      if (intervalPreText == null) {
        break missingId;
      }

      id = R.id.monthGroup;
      RadioGroup monthGroup = ViewBindings.findChildViewById(rootView, id);
      if (monthGroup == null) {
        break missingId;
      }

      id = R.id.options;
      LinearLayout options = ViewBindings.findChildViewById(rootView, id);
      if (options == null) {
        break missingId;
      }

      id = R.id.postEndCount;
      TextView postEndCount = ViewBindings.findChildViewById(rootView, id);
      if (postEndCount == null) {
        break missingId;
      }

      id = R.id.repeatMonthlyByNthDayOfMonth;
      RadioButton repeatMonthlyByNthDayOfMonth = ViewBindings.findChildViewById(rootView, id);
      if (repeatMonthlyByNthDayOfMonth == null) {
        break missingId;
      }

      id = R.id.repeatMonthlyByNthDayOfTheWeek;
      RadioButton repeatMonthlyByNthDayOfTheWeek = ViewBindings.findChildViewById(rootView, id);
      if (repeatMonthlyByNthDayOfTheWeek == null) {
        break missingId;
      }

      id = R.id.repeat_switch;
      MaterialSwitch repeatSwitch = ViewBindings.findChildViewById(rootView, id);
      if (repeatSwitch == null) {
        break missingId;
      }

      id = R.id.weekGroup;
      LinearLayoutWithMaxWidth weekGroup = ViewBindings.findChildViewById(rootView, id);
      if (weekGroup == null) {
        break missingId;
      }

      id = R.id.weekGroup2;
      LinearLayoutWithMaxWidth weekGroup2 = ViewBindings.findChildViewById(rootView, id);
      if (weekGroup2 == null) {
        break missingId;
      }

      return new RecurrencepickerBinding((LinearLayout) rootView, done, endCount, endDate, endGroup,
          endSpinner, freqSpinner, interval, intervalGroup, intervalPostText, intervalPreText,
          monthGroup, options, postEndCount, repeatMonthlyByNthDayOfMonth,
          repeatMonthlyByNthDayOfTheWeek, repeatSwitch, weekGroup, weekGroup2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
