// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import ws.xsoh.etar.R;

public final class RecurrencepickerEndTextBinding implements ViewBinding {
  @NonNull
  private final TextView rootView;

  @NonNull
  public final TextView spinnerItem;

  private RecurrencepickerEndTextBinding(@NonNull TextView rootView,
      @NonNull TextView spinnerItem) {
    this.rootView = rootView;
    this.spinnerItem = spinnerItem;
  }

  @Override
  @NonNull
  public TextView getRoot() {
    return rootView;
  }

  @NonNull
  public static RecurrencepickerEndTextBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecurrencepickerEndTextBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.recurrencepicker_end_text, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecurrencepickerEndTextBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    TextView spinnerItem = (TextView) rootView;

    return new RecurrencepickerEndTextBinding((TextView) rootView, spinnerItem);
  }
}
