// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ListView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class SelectCalendarsFragmentBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final ListView list;

  @NonNull
  public final Button manageSyncSet;

  private SelectCalendarsFragmentBinding(@NonNull CardView rootView, @NonNull ListView list,
      @NonNull Button manageSyncSet) {
    this.rootView = rootView;
    this.list = list;
    this.manageSyncSet = manageSyncSet;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static SelectCalendarsFragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SelectCalendarsFragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.select_calendars_fragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SelectCalendarsFragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.list;
      ListView list = ViewBindings.findChildViewById(rootView, id);
      if (list == null) {
        break missingId;
      }

      id = R.id.manage_sync_set;
      Button manageSyncSet = ViewBindings.findChildViewById(rootView, id);
      if (manageSyncSet == null) {
        break missingId;
      }

      return new SelectCalendarsFragmentBinding((CardView) rootView, list, manageSyncSet);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
