// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class SimpleFrameLayoutMaterialBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final FrameLayout bodyFrame;

  @NonNull
  public final AppBarBinding include;

  @NonNull
  public final LinearLayout mainFrame;

  private SimpleFrameLayoutMaterialBinding(@NonNull LinearLayout rootView,
      @NonNull FrameLayout bodyFrame, @NonNull AppBarBinding include,
      @NonNull LinearLayout mainFrame) {
    this.rootView = rootView;
    this.bodyFrame = bodyFrame;
    this.include = include;
    this.mainFrame = mainFrame;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SimpleFrameLayoutMaterialBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SimpleFrameLayoutMaterialBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.simple_frame_layout_material, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SimpleFrameLayoutMaterialBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.body_frame;
      FrameLayout bodyFrame = ViewBindings.findChildViewById(rootView, id);
      if (bodyFrame == null) {
        break missingId;
      }

      id = R.id.include;
      View include = ViewBindings.findChildViewById(rootView, id);
      if (include == null) {
        break missingId;
      }
      AppBarBinding binding_include = AppBarBinding.bind(include);

      LinearLayout mainFrame = (LinearLayout) rootView;

      return new SimpleFrameLayoutMaterialBinding((LinearLayout) rootView, bodyFrame,
          binding_include, mainFrame);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
