// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class TimeZoneItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView location;

  @NonNull
  public final TextView timeOffset;

  @NonNull
  public final TextView timeZone;

  private TimeZoneItemBinding(@NonNull LinearLayout rootView, @NonNull TextView location,
      @NonNull TextView timeOffset, @NonNull TextView timeZone) {
    this.rootView = rootView;
    this.location = location;
    this.timeOffset = timeOffset;
    this.timeZone = timeZone;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static TimeZoneItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static TimeZoneItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.time_zone_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static TimeZoneItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.location;
      TextView location = ViewBindings.findChildViewById(rootView, id);
      if (location == null) {
        break missingId;
      }

      id = R.id.time_offset;
      TextView timeOffset = ViewBindings.findChildViewById(rootView, id);
      if (timeOffset == null) {
        break missingId;
      }

      id = R.id.time_zone;
      TextView timeZone = ViewBindings.findChildViewById(rootView, id);
      if (timeZone == null) {
        break missingId;
      }

      return new TimeZoneItemBinding((LinearLayout) rootView, location, timeOffset, timeZone);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
