// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AutoCompleteTextView;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ListView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class TimezonepickerviewBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageButton clearSearch;

  @NonNull
  public final AutoCompleteTextView searchBox;

  @NonNull
  public final ListView timezonelist;

  private TimezonepickerviewBinding(@NonNull LinearLayout rootView,
      @NonNull ImageButton clearSearch, @NonNull AutoCompleteTextView searchBox,
      @NonNull ListView timezonelist) {
    this.rootView = rootView;
    this.clearSearch = clearSearch;
    this.searchBox = searchBox;
    this.timezonelist = timezonelist;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static TimezonepickerviewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static TimezonepickerviewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.timezonepickerview, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static TimezonepickerviewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.clear_search;
      ImageButton clearSearch = ViewBindings.findChildViewById(rootView, id);
      if (clearSearch == null) {
        break missingId;
      }

      id = R.id.searchBox;
      AutoCompleteTextView searchBox = ViewBindings.findChildViewById(rootView, id);
      if (searchBox == null) {
        break missingId;
      }

      id = R.id.timezonelist;
      ListView timezonelist = ViewBindings.findChildViewById(rootView, id);
      if (timezonelist == null) {
        break missingId;
      }

      return new TimezonepickerviewBinding((LinearLayout) rootView, clearSearch, searchBox,
          timezonelist);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
