// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class WidgetAllDayItemBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final ImageView agendaItemColor;

  @NonNull
  public final FrameLayout content;

  @NonNull
  public final TextView title;

  @NonNull
  public final FrameLayout widgetRow;

  private WidgetAllDayItemBinding(@NonNull FrameLayout rootView, @NonNull ImageView agendaItemColor,
      @NonNull FrameLayout content, @NonNull TextView title, @NonNull FrameLayout widgetRow) {
    this.rootView = rootView;
    this.agendaItemColor = agendaItemColor;
    this.content = content;
    this.title = title;
    this.widgetRow = widgetRow;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static WidgetAllDayItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static WidgetAllDayItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.widget_all_day_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static WidgetAllDayItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.agenda_item_color;
      ImageView agendaItemColor = ViewBindings.findChildViewById(rootView, id);
      if (agendaItemColor == null) {
        break missingId;
      }

      FrameLayout content = (FrameLayout) rootView;

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.widget_row;
      FrameLayout widgetRow = ViewBindings.findChildViewById(rootView, id);
      if (widgetRow == null) {
        break missingId;
      }

      return new WidgetAllDayItemBinding((FrameLayout) rootView, agendaItemColor, content, title,
          widgetRow);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
